name: Deploy Production Environment

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ vars.PROD_AWS_REGION }}
      S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC Assume Role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::021891595998:role/TerraformUserRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
            terraform_version: "1.12.2"

      - name: Terraform Apply (Prod)
        run: |
          cd infra/environments/prod
          terraform init
          terraform apply -auto-approve